---
title: "Connecting scene direction to year and writer"
author: "Julia Silge"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = FALSE, dpi = 360)
options(width=80, dplyr.width = 150)
library(ggplot2)
library(silgelib)
theme_set(theme_roboto())
```

## Reading in the data

```{r pronoun_bigrams}
library(tidyverse)
library(tidytext)
library(stringr)

all_tsvs <- paste0("setDirections/", list.files(path = "setDirections/", pattern = ".tsv$"))

pronoun_bigrams <- all_tsvs %>%
    map_df(~data_frame(lines = read_lines(.x)) %>%
               filter(str_detect(lines, "^[0-9]")) %>%
               separate(lines, c("line", "text"), sep = "\t") %>%
               mutate(scriptID = as.integer(str_extract(.x, "[\\d]+"))) %>%
               unnest_tokens(bigram, text, token = "ngrams", 
                             n = 2, collapse = FALSE) %>%
               separate(bigram, c("word1", "word2"), sep = " ") %>%
               filter(word1 %in% c("he", "she"))) %>%
    select(scriptID, line, word1, word2)


pronoun_bigrams
```

## Joining the bigrams to other metadata about the scripts


```{r pronoun_imdb, dependson="pronoun_bigrams"}

mapping <- read_csv("full_mapping.csv") %>%
    rename(imdb = imdb_id)

gender <- read_csv("gender.csv") %>%
    filter(important == "1",
           gender != "NULL")

genre <- read_tsv("imdb-genre.tsv") %>%
    rename(imdb = imdb_id)

metadata <- read_tsv("imdb-meta-data-title.tsv") %>%
    select(imdb, year) ## could also get title here if we want later

pronoun_imdb <- pronoun_bigrams %>%
    left_join(mapping, by = c("scriptID" = "id")) 
```

What kind of joining can I do? Year, genre, gender of writers/etc

```{r, dependson="pronoun_imdb"}

pronoun_imdb %>%
    inner_join(genre, by = "imdb") ## to get genre

pronoun_imdb %>%
    inner_join(gender, by = "imdb") ## to get gender of writers, etc

```


## Change by year


```{r words_by_year, dependson="pronoun_imdb"}
words_by_year <- pronoun_imdb %>%
    inner_join(metadata, by = "imdb") %>% ## to get year
    filter(word1 == "she",
           str_detect(word2, "[a-z]+"),
           nchar(word2) > 2,
           !is.na(year),
           year > 1980) %>%
    mutate(year = 5 * year %/% 5) %>%
    add_count(year) %>%
    rename(year_total = n) %>%
    add_count(word2) %>%
    rename(word_total = n) %>%
    filter(word_total > 50) %>%
    count(word2, year, year_total)

slopes <- words_by_year %>%
    nest(-word2) %>%
    mutate(models = map(data, ~ glm(cbind(n, year_total) ~ year, ., 
                                    family = "binomial"))) %>%
    unnest(map(models, tidy)) %>%
    filter(term == "year") %>%
    arrange(estimate)
```


```{r contractions, dependson="words_by_year", fig.width=7, fig.height=5}
words_by_year %>%
    inner_join(slopes %>%
                   top_n(10, estimate), 
               by = "word2") %>%
    ggplot(aes(year, n / year_total, color = word2)) +
    geom_line(alpha = 0.8, size = 1.3) +
    labs(x = NULL, y = "Word frequency",
         title = "Words paired with 'she' in script set directions",
         subtitle = "Many of the words increasing in frequency with time are negative contractions")
```


```{r increasing, dependson="words_by_year", fig.width=7, fig.height=5}
words_by_year %>%
    inner_join(slopes %>%
                   filter(str_detect(word2, "^[^’]*$")) %>%
                   top_n(10, estimate), 
               by = "word2") %>%
    ggplot(aes(year, n / year_total, color = word2)) +
    geom_line(alpha = 0.8, size = 1.3) +
    labs(x = NULL, y = "Word frequency",
         title = "Words paired with 'she' in script set directions",
         subtitle = "More recently, women are more likely to inspect, drift, steal, exhale,  breathe")
```


```{r decreasing, dependson="words_by_year", fig.width=7, fig.height=5}
words_by_year %>%
    inner_join(slopes %>%
                   top_n(-10, estimate), 
               by = "word2") %>%
    ggplot(aes(year, n / year_total, color = word2)) +
    geom_line(alpha = 0.8, size = 1.3) +
    labs(x = NULL, y = "Word frequency",
         title = "Words paired with 'she' in script set directions",
         subtitle = "In the past, women were more likely to jab, snuggle, fling, whirl, shriek")
```


